[package]
name = "web-server"
version = "0.0.0"
edition = "2021"
default-run = "celerserver"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
axum = "0.6.20"
clap = { version = "4.3.4", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4.20"
tokio = { version = "1.32.0", features=["macros", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.4.4", features=["fs"] }

[[bin]]
name = "celerserver"
path = "src/main.rs"
