version: '3'

tasks:
  dev:
    desc: Start server in watch mode
    aliases: [d]
    env:
      CELERSERVER_LOG: INFO
      CELERSERVER_ANSI: 1
      CELERSERVER_PORT: 8173
      CELERSERVER_DOCS_DIR: ../docs/src/.vitepress/dist
      CELERSERVER_APP_DIR: ../web-client/dist
    cmds:
    - cargo watch -B 1 -s "cargo run --bin celerserver -- {{.CLI_ARGS}}"
