[workspace]
resolver = "2"
members = [
    "compiler-core/",
    "compiler-macros/",
    "compiler-types/",
    "compiler-wasm/",
    "web-server/",
]

[profile.release]
lto = true # Link-time optimization
