[workspace]
resolver = "2"
members = [
    "compiler-base/",
    "compiler-core/",
    "compiler-macros/",
    "compiler-wasm/",
    "compiler-wasm/build/",
    "server/",
]

[profile.release]
lto = true # Link-time optimization
