version: '3'

includes:
  base:
    taskfile: ./compiler-base
    dir: ./compiler-base

  core:
    taskfile: ./compiler-core
    dir: ./compiler-core

  wasm:
    taskfile: ./compiler-wasm
    dir: ./compiler-wasm

  docs:
    taskfile: ./docs
    dir: ./docs

  client:
    taskfile: ./web-client
    aliases: [c]
    dir: ./web-client

  server:
    taskfile: ./server
    aliases: [s]
    dir: ./server

  themes:
    taskfile: ./web-themes
    aliases: [th]
    dir: ./web-themes

  docker:
    taskfile: ./docker
    dir: ./docker

tasks:
  install:
    desc: Install development dependencies and packages
    cmds:
    - rustup update
    - cargo install cargo-watch cargo-expand wasm-pack regen-lang
    - cargo install cross --git https://github.com/cross-rs/cross --locked
    - cargo install txtpp
    - task: themes:install
    - task: docs:install
    - task: client:install

  check:
    desc: Check issues in all packages
    deps: [check:ts, check:rs]

  check:ts:
    cmds:
    - task: docs:check
    - task: client:check
    - task: themes:check

  check:rs:
    deps: [base:grammar]
    cmds:
    - cargo clippy --package compiler-macros --all-targets -- -D warnings -D clippy::todo
    - cargo clippy --package compiler-base --features native --all-targets -- -D warnings -D clippy::todo
    - cargo clippy --package compiler-base --features wasm --all-targets -- -D warnings -D clippy::todo
    - cargo clippy --package compiler-core --features native --all-targets -- -D warnings -D clippy::todo
    - cargo clippy --package compiler-core --features wasm --all-targets -- -D warnings -D clippy::todo
    - cargo clippy --package compiler-wasm --all-targets -- -D warnings -D clippy::todo
    - cargo clippy --package celery --all-targets -- -D warnings -D clippy::todo
    - cargo fmt --check

  fix:rs:
    cmds:
    - cargo fmt --all

  build:
    desc: Build production assets
    deps:
    - docs:build
    - build:client
    - build:server

  build:server:
    deps:
    - base:grammar
    dir: ./server
    cmds:
    - cross build --bin celery --release --target x86_64-unknown-linux-musl

  build:client:
    deps:
    - themes:build
    - build:wasm
    cmds:
    - task: client:build

  build:wasm:
    dir: ./compiler-wasm/build
    deps:
    - base:grammar
    cmds:
    - cargo run --bin buildwasm --release

  env:server:
    desc: export the nvim lsp environment variables for server development. Run as `eval $(task env:server)`
    cmds:
    - echo "export LSP_RUST_ANALYZER_EXTRA_ARGS='--exclude compiler-wasm'"

