version: '3'

includes:
  compiler-types:
    taskfile: ./compiler-types
    aliases: [types]
    dir: ./compiler-types

  compiler-core:
    taskfile: ./compiler-core
    aliases: [core]
    dir: ./compiler-core

  compiler-wasm:
    taskfile: ./compiler-wasm
    aliases: [wasm]
    dir: ./compiler-wasm

  docs:
    taskfile: ./docs
    dir: ./docs

  web-client:
    taskfile: ./web-client
    aliases: [client, c]
    dir: ./web-client

  web-server:
    taskfile: ./web-server
    aliases: [server, s]
    dir: ./web-server

  web-themes:
    taskfile: ./web-themes
    aliases: [themes, th]
    dir: ./web-themes

tasks:
  check:
    desc: Check issues in all packages
    deps: [check:ts, check:rs]

  check:ts:
    cmds:
    - task: docs:check
    - task: client:check
    - task: themes:check

  check:rs:
    cmds:
    - cargo fmt --check
    - cargo clippy --all-features --all-targets -- -D warnings -D clippy::todo

  fix:rs:
    cmds:
    - cargo fmt

  docker:
    deps: [build]
    desc: Build docker container
    cmds:
    - docker build -t pistonite/celer . --no-cache

  docker:run:
    desc: Run docker container
    cmds:
    - docker run -p 8000:80 pistonite/celer

  docker:stop:
    desc: Stop docker container
    cmds:
    - docker stop $(docker ps -q -a --filter ancestor=pistonite/celer)

  build:
    desc: Build production assets
    deps:
    - build:docs
    - build:server
    - build:client

  build:docs:
    internal: true
    deps:
    - docs:build
    cmds:
    - rm -rf dist/docs
    - mkdir -p dist/docs
    - cp -r docs/src/.vitepress/dist/* dist/docs

  build:server:
    internal: true
    deps:
    - core:grammar
    cmds:
    - rm -f dist/celerserver
    - mkdir -p dist
    - rustup default stable
    - cross build --bin celerserver --release --target x86_64-unknown-linux-musl
    - cp target/x86_64-unknown-linux-musl/release/celerserver dist/celerserver

  build:client:
    deps:
    - themes:build
    - build:wasm
    - build:types
    cmds:
    - rm -rf dist/app
    - mkdir -p dist/app
    - task: client:build
    - cp -r web-client/dist/* dist/app

  build:wasm:
    dir: ./compiler-wasm
    deps:
    - core:grammar
    cmds:
    - cargo run --bin buildwasm --release > ../.task/build_wasm.out.log 2> ../.task/build_wasm.err.log

  build:types:
    dir: ./compiler-types
    cmds:
    - cargo run --bin buildtypes --release > ../.task/build_types.out.log 2> ../.task/build_types.err.log

