[package]
name = "compiler-core"
version = "0.0.0"
description = "Core logic for the compiler"
edition = "2021"

[dependencies]
compiler-types = { path = "../compiler-types" }
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"

[lib]
name = "celerc"
path = "src/lib.rs"
