[package]
name = "compiler-core"
version = "0.0.0"
description = "Core logic for the compiler"
edition = "2021"

[dependencies]
async-recursion = "1.0.4"
compiler-types = { path = "../compiler-types" }
futures = "0.3.28"
regen-lang = "0.0.6"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
tokio = { version = "1.29.1", features = [
    "macros",
    "rt",
] }
tokio-stream = "0.1.14"

[lib]
name = "celerc"
path = "src/lib.rs"
