[package]
name = "compiler-core"
version = "0.0.0"
description = "Core logic for the compiler"
edition = "2021"

[dependencies]
async-recursion = "1.0.4"
async-trait = "0.1.73"
compiler-types = { path = "../compiler-types" }
derivative = "2.2.0"
futures = "0.3.28"
regen-lang = "0.0.6"
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
serde_yaml = "0.9.25"
thiserror = "1.0.47"
tokio = { version = "1.29.1", features = [
    "macros",
] }
tokio-stream = "0.1.14"

[features]
default = ["tokio/rt-multi-thread"]
wasm = ["tokio/rt"]

[lib]
name = "celerc"
path = "src/lib.rs"
