[package]
name = "docker"
version = "0.0.0"
description = "docker container build scripts"
edition = "2021"
default-run = "buildassets"

[dependencies]
[[bin]]
name = "buildassets"
path = "src/build.rs"
