version: '3'

tasks:
  pull:
    desc: Pull built production asssets locally
    cmds:
    - rm -rf ./dist/*
    - mkdir -p dist/docs
    - mkdir -p dist/app
    - mkdir -p dist/bin
    - cp -r ../docs/src/.vitepress/dist/* dist/docs
    - cp -r ../web-client/dist/* dist/app
    - cp ../target/x86_64-unknown-linux-musl/release/celerserver dist/bin
    - chmod +x ./make-version.sh
    - ./make-version.sh 0.0.0-dev docker

  build:
    desc: Build docker container locally (requires building assets first)
    deps: [pull]
    cmds:
    - task: build-container

  build-container:
    cmds:
    - docker build -t pistonite/celer . {{.CLI_ARGS}}

  run:
    desc: Run docker container
    cmds:
      - task: run-image
        vars:
          IMAGE: pistonite/celer

  run-image:
    desc: Run docker container
    cmds:
      - docker run -p 8000:80 -e CELERSERVER_SITE_ORIGIN=http://pistonite.local {{.IMAGE}}

  stop:
    desc: Stop docker container
    cmds:
    - docker stop $(docker ps -q -a --filter ancestor=pistonite/celer)
