version: '3'

tasks:
  dev:
    desc: Start server in watch mode
    aliases: [d]
    dotenv:
    - dev.env
    cmds:
    - cargo watch -B 1 -s "cargo run --bin celery {{.CLI_ARGS}}"

  run:
    desc: Start server
    dotenv:
    - dev.env
    cmds:
    - cargo run --bin celery {{.CLI_ARGS}}

  watch:
    desc: Run server tests in watch mode
    cmds:
    - cargo watch -x test

  test:
    desc: Run server tests
    cmds:
    - cargo test {{.CLI_ARGS}}
