version: '3'

tasks:
  run:
    desc: Start server
    dotenv:
    - dev.env
    cmds:
    - cargo build --bin celery {{.CLI_ARGS}}
    - cargo run --manifest-path ./boot/Cargo.toml --bin celery-boot {{.CLI_ARGS}}

  watch:
    desc: Run server tests in watch mode
    cmds:
    - cargo watch -x test

  test:
    desc: Run server tests
    cmds:
    - cargo test {{.CLI_ARGS}}
