version: '3'

tasks:
  dev:
    desc: Start server in watch mode
    aliases: [d]
    dotenv:
    - dev.env
    cmds:
    - cargo watch -B 1 -s "cargo run --bin celery {{.CLI_ARGS}}"

  run:
    desc: Start server
    dotenv:
    - dev.env
    cmds:
    - cargo run --bin celery {{.CLI_ARGS}}

  watch:
    desc: Run server tests in watch mode
    cmds:
    - cargo watch -x test

  test:
    desc: Run server tests
    cmds:
    - cargo test {{.CLI_ARGS}}

  package:
    desc: Build release package (including bootstrap binary)
    cmds:
    - rm -rf bin
    - mkdir -p bin
    - cargo build --bin celery --release --target x86_64-unknown-linux-musl
    - cp ../target/x86_64-unknown-linux-musl/release/celery bin
    - cargo build --bin celery-boot --release --target x86_64-unknown-linux-musl
    - cp ../target/x86_64-unknown-linux-musl/release/celery-boot bin
