[package]
name = "compiler-macros"
version = "0.0.0"
description = "(Proc) Macros for the compiler core"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.69"
quote = "1.0.33"
# serde-wasm-bindgen = { version = "0.6.0", optional = true }
syn = "2.0.38"
# wasm-bindgen = { version = "0.2.87", optional = true }

# [feature]
# default = ["wasm"]
# wasm = ["dep:wasm-bindgen", "dep:serde-wasm-bindgen"]

[lib]
proc-macro = true
name = "celercmacros"
path = "src/lib.rs"
