version: '3'

tasks:
  install:
    cmds:
    - npm install

  ci:
    cmds:
    - npm ci

  dev:
    desc: Watch for changes in themes and rebuild
    aliases: [d]
    cmds:
    - cargo watch -s "node build.js -- {{.CLI_ARGS}}"

  build:
    desc: Build theme assets and copy them to web-client
    cmds:
    - node build.js

  check:
    desc: Check for linting and formatting issues in theme files
    aliases: [lint]
    cmds:
    - task: prettier
      vars:
        PRETTIER_ARGS: --check

  fix:
    desc: Fix linting and formatting issues in theme files
    cmds:
    - task: prettier
      vars:
        PRETTIER_ARGS: --write
  
  prettier:
    cmds:
    - npx prettier "./**/*.{ts,tsx,json,js,jsx,cjs,css,html}" {{.PRETTIER_ARGS}} --config ../web-client/.prettierrc.cjs
