version: '3'

tasks:
  dev:
    desc: Start web client in watch mode
    aliases: [d]
    cmds:
    - npm run dev -- --host

  build:
    desc: Build web client assets
    aliases: [b]
    cmds:
    - npm run build
    - node tools/post-build.cjs
    - rm dist/index.html
