version: '3'

tasks:
  txtpp:
    desc: Preprocess source files
    cmds:
    - echo "txtpp disabled for now"

  dev:
    desc: Start docs in watch mode
    aliases: [d]
    cmds:
    - npm run dev

  build:
    desc: Build docs assets
    aliases: [b]
    deps: [txtpp]
    cmds:
    - npm run build


