version: '3'

tasks:
  install:
    cmds:
    - npm install

  ci:
    cmds:
    - npm ci

  dev:
    desc: Start docs in watch mode
    cmds:
    - npx vitepress dev src --port 3173 --host

  build:
    desc: Build docs assets
    deps: [txtpp]
    cmds:
    - npx vitepress build src > /dev/null 2> /dev/null

  check:
    desc: Check for issues in the docs
    cmds:
    - txtpp verify src -r
    - task: prettier
      vars:
        PRETTIER_ARGS: --check

  fix:
    desc: Fix issues in the docs
    deps: [txtpp]
    cmds:
    - task: prettier
      vars:
        PRETTIER_ARGS: --write

  txtpp:
    desc: Preprocess source files
    cmds:
      - echo "txtpp disabled for now"

  prettier:
    cmds:
    - npx prettier "./**/*.{ts,tsx,json,js,jsx,cjs,css,html}" {{.PRETTIER_ARGS}} --config ../web-client/.prettierrc.cjs
