name: Lint
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint-typescript:
    name: Lint TypeScript Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: dtolnay/rust-toolchain@stable
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: txtpp
    - run: task themes:ci client:ci docs:ci --output group
    - run: task themes:check client:check docs:check --output group

  lint-rust:
    name: Lint Rust Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: regen-lang
    - run: task check:rs
