name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-typescript:
    name: Test TypeScript Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - uses: dtolnay/rust-toolchain@stable
    - uses: baptiste0928/cargo-install@v2
      with:
        crate: regen-lang
    - uses: baptiste0928/cargo-install@v2
      with:
        crate: wasm-pack
    - run: task themes:ci client:ci --output group
    - run: task themes:build build:wasm build:types --output group
    - run: task client:test

  test-rust:
    name: Test Rust Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dtolnay/rust-toolchain@stable
    - uses: baptiste0928/cargo-install@v2
      with:
        crate: regen-lang
    - run: task core:grammar
    - run: cargo test --all-features --all-targets
