name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-typescript:
    name: Test TypeScript Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: regen-lang
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: wasm-pack
    - run: task client:ci --output group
    - run: task build:wasm --output group
    - run: task client:test

  test-rust:
    name: Test Rust Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: regen-lang
    - run: task base:test -- --release
    - run: task core:test -- --release
    - run: task server:test -- --release
